source 'https://bitbucket.org/qranioios/specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.4'

use_frameworks!

target '${POD_NAME}_Example' do
  pod '${POD_NAME}', :path => '../'

  target '${POD_NAME}_Tests' do
    inherit! :search_paths

    ${INCLUDED_PODS}
  end
end
